name: Publish to ComfyUI Registry

on:
  push:
    paths:
      - 'pyproject.toml'
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g @comfy-org/cli
      - run: comfy node publish --token ${{ secrets.REGISTRY_ACCESS_TOKEN }}