# GitHub CI build pipeline
name: {{ cookiecutter.project_slug }} CI build

on:
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: {% raw %} ${{ matrix.os }} {% endraw %}
    env:
      PYTHONIOENCODING: "utf8"
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: {% raw %} ${{ matrix.python-version }} {% endraw %}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run Linting
        run: |
          ruff check .
      - name: Run Tests
        run: |
          pytest tests/
